# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{profigure}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Friedman"]
  s.date = %q{2010-05-18}
  s.description = %q{profigure aims to be a drop in replacement for configuring your apps in a railsy way.}
  s.email = %q{asher.friedman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/profigure.rb",
     "lib/profigure/hash_extensions.rb",
     "lib/profigure/profigure.rb",
     "profigure.gemspec",
     "spec/profigure_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test_config/arrays.yml",
     "spec/test_config/defaults.yml",
     "spec/test_config/erb.yml",
     "spec/test_config/like_nested.yml",
     "spec/test_config/nested.yml",
     "spec/test_config/overrides.yml",
     "spec/test_config/test.yml"
  ]
  s.homepage = %q{http://github.com/joelash/profigure}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Replacing the cons with pros in configuration}
  s.test_files = [
    "spec/profigure_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mostash>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<mostash>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<mostash>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

